sudo: required
dist: trusty

language: nodejs

matrix:
  include:
    - os: osx
    - os: linux
#      env: CC=clang CXX=clang++ npm_config_clang=1
      compiler: clang

env:
  - CXX=g++-4.8

node_js:
  - 11

cache:
  yarn: true
  directories:
    - node_modules

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - icnsutils
      - rpm
      - curl

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - yarn install
  - yarn dist
